name: main

on:
  push:
    branches: [master, test-me-*]
  pull_request:

jobs:
  main-linux:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.0.0
    with:
      env: '["py38", "py39", "py310"]'
      os: ubuntu-latest
